export const FETCH_PUBLISHERS = 'FETCH_PUBLISHERS';
export const FETCH_PUBLISHER_ROUTES = 'FETCH_PUBLISHER_ROUTES';
export const CHANGE_PUBLISHER_ROUTE = 'CHANGE_PUBLISHER_ROUTE';
export const ADD_NEW_VARIATION = 'ADD_NEW_VARIATION';
export const UPDATE_VARIATION_FORM = 'UPDATE_VARIATION_FORM';
export const POST_PUBLISHER_ROUTE = 'POST_PUBLISHER_ROUTE';
export const RESET_PUBLISHER_ONE = 'RESET_PUBLISHER_ONE';
export const UPDATE_ROUTE_FORM = 'UPDATE_ROUTE_FORM';
export const UPDATE_ROUTE_VARIATION_FORM = 'UPDATE_ROUTE_VARIATION_FORM';
export const PUBLISHER_DATA_TO_ROUTE = 'PUBLISHER_DATA_TO_ROUTE';

export const UPDATE_NOOFPLAYERS = 'UPDATE_NOOFPLAYERS';
export const UPDATE_PLAYERNAMES = 'UPDATE_PLAYERNAMES';
export const SWITCH_INPUT_TYPE = 'SWITCH_INPUT_TYPE';
